[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "phishing-email-analyzer"
version = "0.1.0"
description = "Analizador educativo y offline de señales sospechosas en correos .eml"
readme = "README.md"
requires-python = ">=3.11"
license = { text = "MIT" }
authors = [
  { name = "AVillegas118" }
]
dependencies = []

[project.scripts]
phishcheck = "phishing_email_analyzer.cli:main"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

